models/alarmas.py
from utils.db import db

class Alarma(db.Model):
    id_alarma = db.Column(db.Integer, primary_key = True)
    nombre = db.Column(db.String(100))
    hora_inicio = db.Column(db.String(100))
    estado = db.Column(db.Boolean, default=False)

    def __init__(self, nombre, hora_inicio, estado):
        self.nombre = nombre
        self.hora_inicio = hora_inicio
        self.estado = estado

models/pomodoro.py
from utils.db import db

class Pomodoro(db.Model):
    id_pomodoro = db.Column(db.Integer, primary_key = True)
    duracion_trabajo = db.Column(db.Integer)
    duracion_descanso = db.Column(db.Integer)

    def __init__(self, duracion_trabajo, duracion_descanso):
        self.duracion_trabajo = duracion_trabajo
        self.duracion_descanso = duracion_descanso

models/usuarios.py
from flask_login import UserMixin
from utils.db import db

class Usuario(db.Model, UserMixin):
    id_usuario = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(100))
    email = db.Column(db.String(100))
    contrasena = db.Column(db.String(100))

    def __init__(self, nombre, email, contrasena):
        self.nombre = nombre
        self.email = email
        self.contrasena = contrasena

    def get_id(self):
        return self.id_usuario

app.py
from flask import  Flask
from routes.pomodoro import pomodoro
from routes.usuarios import usuarios
from routes.alarmas import alarmas
from routes.cronometro import cronometros
from routes.temporizador import temporizadores
from flask_sqlalchemy import SQLAlchemy
from utils.db import db
from flask_login import LoginManager
from models.usuarios import Usuario


app = Flask(__name__)

app.secret_key = "secret_key"
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:jAZCoqCuPCosufYyDcuSIKCHWAjfFXNi@roundhouse.proxy.rlwy.net:45746/railway'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['WTF_CSRF_ENABLED'] = True

db.init_app(app)
login_manager_app = LoginManager(app)
@login_manager_app.user_loader
def load_user(id):
    return Usuario.query.filter_by(id_usuario=id).first()

app.register_blueprint(pomodoro)
app.register_blueprint(usuarios)
app.register_blueprint(alarmas)
app.register_blueprint(cronometros)
app.register_blueprint(temporizadores)

routes/alarmas.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify
from models.alarmas import Alarma
from utils.db import db
from flask_login import login_required
from datetime import datetime

alarmas = Blueprint('alarma', __name__)

@alarmas.route('/alarma')
@login_required
def alarma():
    alarmas = Alarma.query.all()
    hora_actual = datetime.now().time() 

    mostrar_modal = False

    for alarma in alarmas:
        if alarma.hora_inicio == hora_actual.strftime('%H:%M'):
            mostrar_modal = True
            break

    csrf_enabled = current_app.config.get('WTF_CSRF_ENABLED', True)
    return render_template('alarma.html', alarmas=alarmas, csrf_enabled=csrf_enabled, mostrar_modal=mostrar_modal)

@alarmas.route('/verificar_alarma')
@login_required
def verificar_alarma():
    alarmas = Alarma.query.all()
    hora_actual = datetime.now().time() 

    mostrar_modal = False
    for alarma in alarmas:
        if alarma.hora_inicio == hora_actual.strftime('%H:%M'):
            mostrar_modal = True
            break

    return jsonify(mostrar_modal=mostrar_modal)

@alarmas.route('/crearAlarma', methods=['POST'])
@login_required
def addContact():
    if request.method == 'POST':
        nombre = request.form['nombre']
        hora_inicio = request.form['hora_inicio']
        

        new_alarm = Alarma(nombre, hora_inicio, 1)

        db.session.add(new_alarm)
        db.session.commit()
        flash('Alarm added successfully!')
        
        return redirect(url_for('alarma.alarma'))


@alarmas.route('/alarma/<id>', methods = ['POST','GET'])
@login_required
def update(id):
    alarma = Alarma.query.get(id)
    if request.method == 'POST':
        alarma.nombre = request.form['nombre']
        alarma.hora_inicio = request.form['hora_inicio']

        if request.form['estado'] == "true":
            alarma.estado = 1
        else:
            alarma.estado = 0

        db.session.commit()
        flash("Alarma updated successfully!!")
        return redirect(url_for('alarma.alarma'))
    csrf_enabled = current_app.config.get('WTF_CSRF_ENABLED', True) 
    mostrar_modal = False
    return render_template('update.html', alarma = alarma,csrf_enabled=csrf_enabled,mostrar_modal=mostrar_modal)

@alarmas.route('/deleteAlarma/<id>')
@login_required
def delete(id):
    alarma = Alarma.query.get(id)
    db.session.delete(alarma)
    db.session.commit()

    flash("Alarma deleted successfully!!")

    return redirect(url_for('alarma.alarma'))

routes/cronometro.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from flask_login import login_required

cronometros = Blueprint('cronometro', __name__)

@cronometros.route('/cronometro')
@login_required
def cronometro():
    return render_template('cronometro.html')

routes/pomodoro.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from models.pomodoro import Pomodoro
from utils.db import db
from flask_login import login_required

pomodoro = Blueprint('pomodoro', __name__)

@pomodoro.route('/pomodoro')
@login_required
def index():    
    pomodoro = Pomodoro.query.all()
    return render_template('pomodoro.html', pomodoro = pomodoro)

@pomodoro.route('/newPomodoro', methods=['POST'])
@login_required
def addContact():
    duracion_trabajo = request.form['duracion_trabajo']
    duracion_descanso = request.form['duracion_descanso']
    
    new_pomodoro = Pomodoro(duracion_trabajo, duracion_descanso)
    db.session.add(new_pomodoro)
    db.session.commit()

    flash("Pomodoro added successfully!")
    return redirect(url_for('contacts.index'))

@pomodoro.route('/pomodoro/<id>', methods = ['POST','GET'])
@login_required
def update(id):
    pomodoro = Pomodoro.query.get(id)
    if request.method == 'POST':
        pomodoro.duracion_trabajo = request.form['duracion_trabajo']
        pomodoro.duracion_descanso = request.form['duracion_descanso']

        db.session.commit()
        flash("Pomodoro updated successfully!!")
        return redirect(url_for('contacts.index'))
    
    return render_template('update.html', contact = pomodoro)

@pomodoro.route('/deletePomodoro/<id>')
@login_required
def delete(id):
    pomodoro = Pomodoro.query.get(id)
    db.session.delete(pomodoro)
    db.session.commit()

    flash("Pomodoro deleted successfully!!")

    return redirect(url_for('contacts.index'))

routes/temporizador.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from flask_login import login_required

temporizadores = Blueprint('temporizador', __name__)

@temporizadores.route('/temporizador')
@login_required
def temporizador():
    return render_template('temporizador.html')

routes/usuarios.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from models.usuarios import Usuario
from utils.db import db
from flask_login import LoginManager, login_user, logout_user

usuarios = Blueprint('usuarios', __name__)

@usuarios.route('/')
def index():
    return redirect(url_for('usuarios.login'))


@usuarios.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        usuario = Usuario.query.filter_by(nombre=username).first()
        
        if(usuario != None):
            login_user(usuario)
            return redirect(url_for('alarma.alarma'))
        
        flash("Usuario not found!")
        return render_template('login.html')
    else:
        return render_template('login.html')
    
@usuarios.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('usuarios.login'))
    
@usuarios.route('/crearUsuario', methods=['GET','POST'])
def addUser():
    if request.method == 'POST':
        nombre = request.form['nombre']
        email = request.form['email']
        contrasena = request.form['contrasena']
        
        new_usuario = Usuario(nombre, email, contrasena)
        db.session.add(new_usuario)
        db.session.commit()

        flash("Usuario added successfully!")
        return redirect(url_for('usuarios.login'))
    else:
        return render_template('crearUsuario.html')

templates/alarma.html
{% extends "layout.html" %} {% block body %}

<div>
  <div class="container-alarma">
    <h1 class="title">Alarmas</h1>

    <audio
      id="alert-sound2"
      src="{{url_for('static', filename='alert.mp3')}}"
    ></audio>

    <!-- Modal -->
    {% if mostrar_modal %}
    <div id="myModal" class="modal" style="display: block">
      <div class="modal-content">
        <span class="close">&times;</span>
        <p>¡Es hora de la alarma!</p>
      </div>
    </div>
    {% endif %} {% include 'partials/_message.html' %}
    <form action="/crearAlarma" method="POST">
      <div>
        <div>
          <label for="nombre">Nombre:</label>
          {% if csrf_enabled %}
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          {% endif %}
          <input
            type="text"
            name="nombre"
            placeholder="Coloque el nombre de la alarma"
            autofocus
            required
          />
        </div>

        <div>
          <label for="hora_inicio">Hora:</label>
          <input
            type="time"
            name="hora_inicio"
            placeholder="Escriba la hora a la que sonará"
            required
          />
        </div>

        <button>Create</button>
      </div>
    </form>

    <div class="container-alarmas-creadas">
      {% for alarma in alarmas %}
      <div class="grid-alarmas-creadas-item">
        <div>
          <div class="container-title-item-alarma-grid">
            <h5>{{ alarma.nombre }}</h5>
            <div>
              <a href="{{ url_for('alarma.update', id=alarma.id_alarma) }}"
                >editar</a
              >
              <a href="{{ url_for('alarma.delete', id=alarma.id_alarma) }}"
                >eliminar</a
              >
            </div>
          </div>
          <p class="hora_inicio">{{ alarma.hora_inicio }}</p>
          <p class="estado">
            {% if alarma.estado %} Activo {% else %} Desactivado {% endif %}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/crearUsuario.html
{% extends 'layout.html' %}

{% block title %}
  Flask SQLAlchemy CRUD | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">

    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}

      <!-- FORM -->
      <form action="/crearUsuario" method="POST">
        <div>
          <h1>Crear Usuario</h1>
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
          <div>
            <label for="nombre" class="label">Nombre de usuario:</label>
            <input
              type="text"
              name="nombre"
              placeholder="Digite su nombre de usuario"
              autofocus
            />
          </div>
          <div>
            <label for="email" class="label">Correo:</label>
            <input type="email" name="email" placeholder="Digite su email" required />
          </div>
          <div>
            <label for="contrasena" class="label">Contraseña:</label>
            <input
              type="password"
              name="contrasena"
              placeholder="Digite su contraseña"
              required
            />
          </div>
      
          <button type="submit">create</button>
          <h5>Valores de prueba usuario: usuario contraseña: 123</h5>
        </div>
      </form>
    </div>
  </div>
    </div>
{% endblock %}

templates/cronometro.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Timemaster</title>
    <!-- <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    /> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Playwrite+MX:wght@100..400&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Playwrite+MX:wght@100..400&family=Space+Grotesk:wght@300..700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include 'partials/_navbar.html' %}

    <div>
      <div>
        <div>
          <h1 class="title">Cronómetro</h1>
          <div id="cronometro" class="display-1 contador">00:00:00.000</div>
          <br />
          <button id="btn-iniciar">Iniciar</button>
          <button id="btn-detener">Detener</button>
          <button id="btn-reiniciar">Reiniciar</button>
          <button id="btn-reanudar" style="display: none">Reanudar</button>
        </div>
      </div>
    </div>

    <!-- scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        var cronometro;
        var tiempoInicio;
        var corriendo = false;
        var tiempoPausado = 0; // Variable para almacenar el tiempo transcurrido al pausar

        function iniciarCronometro() {
          document.getElementById("btn-reanudar").style.display =
            "inline-block";
          if (!corriendo) {
            corriendo = true;
            tiempoInicio = new Date().getTime();
            if (tiempoPausado > 0) {
              tiempoInicio -= tiempoPausado; // Restablece el tiempo inicial descontando el tiempo pausado
            }
            cronometro = setInterval(actualizarCronometro, 10);
          }
        }

        function detenerCronometro() {
          if (corriendo) {
            corriendo = false;
            clearInterval(cronometro);
            tiempoPausado = new Date().getTime() - tiempoInicio; // Calcula el tiempo transcurrido desde el inicio
          }
        }

        function reiniciarCronometro() {
          detenerCronometro();
          tiempoPausado = 0;
          document.getElementById("cronometro").innerText = "00:00:00.000";
        }

        function actualizarCronometro() {
          if (corriendo) {
            var tiempoActual = new Date().getTime();
            var tiempoTranscurrido = tiempoActual - tiempoInicio;

            var horas = Math.floor(tiempoTranscurrido / 3600000);
            var minutos = Math.floor((tiempoTranscurrido % 3600000) / 60000);
            var segundos = Math.floor((tiempoTranscurrido % 60000) / 1000);
            var milisegundos = tiempoTranscurrido % 1000;

            horas = horas < 10 ? "0" + horas : horas;
            minutos = minutos < 10 ? "0" + minutos : minutos;
            segundos = segundos < 10 ? "0" + segundos : segundos;

            var tiempoFormateado =
              horas + ":" + minutos + ":" + segundos + "." + milisegundos;

            document.getElementById("cronometro").innerText = tiempoFormateado;
          }
        }

        document
          .getElementById("btn-iniciar")
          .addEventListener("click", function () {
            iniciarCronometro();
          });

        document
          .getElementById("btn-detener")
          .addEventListener("click", function () {
            detenerCronometro();
          });

        document
          .getElementById("btn-reiniciar")
          .addEventListener("click", function () {
            reiniciarCronometro();
          });

        document
          .getElementById("btn-reanudar")
          .addEventListener("click", function () {
            iniciarCronometro();
          });
      });
    </script>
  </body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Timemaster</title>
    <!-- <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    /> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Playwrite+MX:wght@100..400&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Playwrite+MX:wght@100..400&family=Space+Grotesk:wght@300..700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include 'partials/_navbar.html' %}

    <div>{% block body %} {% endblock %}</div>

    <!-- scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script>
      const alertSound2 = document.getElementById("alert-sound2");
      document.addEventListener("DOMContentLoaded", function () {
        let mostrarModal = false;
        let pausaActivada = false;

        function verificarAlarma() {
          fetch("http://127.0.0.1:5000/verificar_alarma")
            .then((response) => response.json())
            .then((data) => {
              if (data.mostrar_modal) {
                console.log(data.mostrar_modal);
                mostrarModal = true;
              } else {
                console.log(false);
                mostrarModal = false;
              }
            })
            .catch((error) => {
              console.error("Error:", error);
              mostrarModal = false;
            });
        }

        let modal = document.getElementById("myModal");
        let ejecutado = localStorage.getItem("ejecutado");
        console.log("ejeeejeje" + ejecutado);
        console.log(typeof ejecutado);

        // Mostrar el modal si mostrarModal es true
        function actualizarModal() {
          if (mostrarModal) {
            if (ejecutado === "null") {
              location.reload();
              localStorage.setItem("ejecutado", false);
              console.log("ejecutado" + ejecutado);
            }
            let span = document.getElementsByClassName("close")[0];
            span.onclick = function () {
              modal.style.display = "none";
              alertSound2.pause();
              pausaActivada = true;
            };
            if (!pausaActivada) {
              alertSound2.play();
              modal.style.display = "block";
            }
          } else {
            modal.style.display = "none";
            alertSound2.pause();
          }
        }

        // Verificar alarmas cada segundo

        if (mostrarModal == false) {
          setInterval(actualizarModal, 5000);
          setInterval(verificarAlarma, 10000);
        } else {
          setInterval(actualizarModal, 60000);
          setInterval(verificarAlarma, 60000);
        }
        // Llamar a verificarAlarma inmediatamente después de cargar la página
        verificarAlarma();
        actualizarModal();
      });
    </script>
  </body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block title %}
  Flask SQLAlchemy CRUD | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">

    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}

      <!-- FORM -->
      {%  include 'partials/_taskForm.html' %}
    </div>
  </div>
    </div>




{% endblock %}

templates/partials/_message.html
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %} {% endwith %}

templates/partials/_navbar.html
<nav class="navbar">
  <a href="/alarma" class="title">Timemaster </a>
  <div id="navbarNav">
    <ul class="navItems">
      <li>
        <a aria-current="page" href="/cronometro">cronometro</a>
      </li>
      <li>
        <a aria-current="page" href="/temporizador">temporizador</a>
      </li>
      <li>
        <a aria-current="page" href="/pomodoro">pomodoro</a>
      </li>
      <li>
        <a aria-current="page" href="/alarma">alarma</a>
      </li>
      <li>
        <a aria-current="page" href="{{ url_for('usuarios.logout')}}">logout</a>
      </li>
    </ul>
  </div>
</nav>

templates/partials/_taskForm.html
<form action="/login" method="POST">
  <div>
    <h1>Login</h1>
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
    <div>
      <label for="username" class="label">Nombre de usuario:</label>
      <input
        type="text"
        name="username"
        placeholder="Digite su nombre de usuario"
        autofocus
      />
    </div>

    <div>
      <label for="password" class="label">Contraseña:</label>
      <input
        type="password"
        name="password"
        placeholder="Digite su contraseña"
        required
      />
    </div>

    <button type="submit">login</button>
    <h5>Valores de prueba usuario: usuario contraseña: 123</h5>
  </div>
</form>

templates/update.html
{% extends "layout.html" %} {% block title %}Update Alarma{% endblock %} {%
block body %}
<div class="container-update-form">
  <h1 class="title">Update Alarma</h1>
  <form
    method="POST"
    action="{{ url_for('alarma.update', id=alarma.id_alarma) }}"
  >
    <div>
      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        value="{{ alarma.nombre }}"
        required
      />
    </div>
    <div>
      <label for="hora_inicio">Hora de inicio:</label>
      <input
        type="time"
        id="hora_inicio"
        name="hora_inicio"
        value="{{ alarma.hora_inicio }}"
        required
      />
    </div>
    <div>
      <label for="estado">Estado:</label>
      <select id="estado" name="estado" required>
        <option value="true" {% if alarma.estado %}selected{% endif %}>
          Activa
        </option>
        <option value="false" {% if not alarma.estado %}selected{% endif %}>
          Inactiva
        </option>
      </select>
    </div>
    {% if csrf_enabled %}
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    {% endif %}
    <button type="submit" class="button">Actualizar</button>
  </form>
</div>
{% endblock %}